Feature/multiple adapter support
joomla-projects/media-manager-improvement pull request #244
Opened 2017-06-09 17:28 UTC by kasvith

Pull Request for Issue #190  .

### Summary of Changes
- Added config param to Local File System plugin for set Display Name
- Added Foo File System Plugin
- Added multiple adapter support to API
- Added multiple adapter support to Controller
- Injected config params to Media View

### Testing Instructions
- Discover **Foo Filesystem**
- Go to NMM
- HTTP 200OK message will be shown, ignore for now
- Try these urls on browser
http://localhost/media-manager-improvement/administrator/index.php?option=com_media&format=json&task=api.files&path=local:/banners

http://localhost/media-manager-improvement/administrator/index.php?option=com_media&format=json&task=api.files&path=foo:/

### Expected result
- A JSON response containing all the files

### Actual result

@dneukirchen @dgt41 if this is ok we can go with frontend implementation

2017-06-09 17:35 UTC, dgt41 commented on administrator/components/com_media/models/api.php
> +			for ($i = 0; $i < count($results); $i++)
`for ($i = 0, $l = count($results); $i < $l; $i++)` is faster

2017-06-09 17:36 UTC, dgrammatiko approved these changes

2017-06-09 17:37 UTC, kasvith commented on administrator/components/com_media/models/api.php
> +			for ($i = 0; $i < count($results); $i++)
but count($results) counted when loop initialize right?

2017-06-09 17:39 UTC, kasvith commented on administrator/components/com_media/models/api.php
> +			for ($i = 0; $i < count($results); $i++)
@dgt41 if $results = null, count($results) would return a 0

2017-06-09 17:51 UTC, yvesh commented on administrator/components/com_media/controllers/api.json.php
> +		$accountID = "";
Codestyle - please indent all = on the same

```
$pathInfo = ..
$path       = ..
```

2017-06-09 17:51 UTC, yvesh commented on administrator/components/com_media/controllers/api.json.php
> +		$adapter = $adapterInfo[0];
you can use list instead :-)

2017-06-09 17:52 UTC, kasvith commented on administrator/components/com_media/controllers/api.json.php
> +		$accountID = "";
sure

2017-06-09 17:54 UTC, dgt41 commented on administrator/components/com_media/models/api.php
> +			for ($i = 0; $i < count($results); $i++)
if it's in the second part of the for then count() is calculated in every iteration ;)

2017-06-09 17:55 UTC, yvesh commented on administrator/components/com_media/models/api.php
> +		}
You don't need else here, as you do a return ;-)

2017-06-09 17:55 UTC, yvesh commented on administrator/components/com_media/models/api.php
> +			throw new Exception('Requested media file adapter was not found', 300);
Why 300? :D

2017-06-09 17:55 UTC, yvesh commented on administrator/components/com_media/views/media/tmpl/default.php
> +		$info = new stdClass;
Indention on the longest equal sign :-)

2017-06-09 17:57 UTC, kasvith commented on administrator/components/com_media/models/api.php
> +			throw new Exception('Requested media file adapter was not found', 300);
anything better 🥇

2017-06-10 06:54 UTC, laoneo commented on administrator/components/com_media/views/media/tmpl/default.php
> +function getProviderInfo()
This needs to be done in the view, the template files should not have functions.

2017-06-10 06:54 UTC, laoneo commented on plugins/filesystem/local/local.xml
> +						name="display_name"
I guess there is one tab to much.

2017-06-10 06:54 UTC, laoneo commented on plugins/filesystem/local/local.xml
> +						label="Display Name"
Needs to be a a translatable key.

2017-06-10 06:54 UTC, laoneo commented on plugins/filesystem/local/local.xml
> +						description="Local Filesystem plugin"
Needs to be a a translatable key.

2017-06-10 06:54 UTC, laoneo commented on plugins/filesystem/foo/foo.xml
> +						name="display_name"
A tab to much.

2017-06-10 06:54 UTC, laoneo commented on plugins/filesystem/foo/foo.php
> +		$root = JPATH_ROOT . '/fooFiles';
Should we not ensure that the folder exists?

2017-06-10 06:54 UTC, laoneo commented on administrator/components/com_media/views/media/tmpl/default.php
> +		$params            = new JRegistry($provider->params);
Should be Joomla\Registry\Registry, JRegistry is deprecated.

2017-06-10 06:54 UTC, laoneo commented on administrator/components/com_media/views/media/tmpl/default.php
> +	$providerInfo = JPluginHelper::getPlugin('filesystem');
Use the namespaced class.

2017-06-10 06:54 UTC, laoneo commented on administrator/components/com_media/models/api.php
> +			$config['providers'] = JPluginHelper::getPlugin('filesystem');
Use the namespaced class.

2017-06-10 06:57 UTC, kasvith commented on plugins/filesystem/foo/foo.php
> +		$root = JPATH_ROOT . '/fooFiles';
its a mock file system, so i did not put much effort on that

2017-06-10 09:12 UTC, kasvith commented on plugins/filesystem/foo/foo.xml
> +						name="display_name"
we will remove foo related files soon

2017-06-12 07:19 UTC, dneukirchen requested changes

2017-06-12 07:19 UTC, dneukirchen commented on administrator/components/com_media/controllers/api.json.php
> +		list($adapter, $account)  = array_merge(explode('-', $adapterInfo), array(""));
This shows how multiple accounts can be integrated. 
Imo we should not include it until we really use it. Please remove the account handling.

2017-06-12 07:19 UTC, dneukirchen commented on administrator/components/com_media/views/media/tmpl/default.php
> +	'defaultFileSystem'       => 'local',
This is hardcoded and should be removed. You can a "is_default: true" to the providers array.

2017-06-12 07:19 UTC, dneukirchen commented on administrator/components/com_media/models/api.php
> +			$this->providers = $config['providers'];
What happens when config['providers'] is set?
This should be moved outside of the if block to allow setting providers via config.

2017-06-12 07:19 UTC, dneukirchen commented on administrator/components/com_media/models/api.php
> +			$this->adapters = $adapters;
Same as above: What happens when config['fileadapter'] is set?
This should be moved outside of the if block to allow setting fileadapter via config.

Additionaly the naming should be improved: you use singular config['fileadapter'] and set it to plural $adapters.

2017-06-12 07:19 UTC, dneukirchen commented on administrator/components/com_media/models/api.php
> +		throw new Exception('Requested media file adapter was not found', 500);
Change to InvalidArgumentException to be more expressive.

2017-06-12 07:26 UTC, kasvith commented on administrator/components/com_media/models/api.php
> +			$this->adapters = $adapters;
Sorry for typo

@laoneo do we want to remove this config part from api? It was there in the original MM code when i modified it

2017-06-12 07:27 UTC, kasvith commented on administrator/components/com_media/views/media/tmpl/default.php
> +	'defaultFileSystem'       => 'local',
I'll fix that

2017-06-12 07:28 UTC, laoneo requested changes

2017-06-12 07:28 UTC, laoneo commented on administrator/components/com_media/models/api.php
> +			$config['providers'] = Joomla\CMS\Plugin\PluginHelper::getPlugin('filesystem');
This assignment is not needed at all. It makes sense when you want to inject the providers trough the config.

2017-06-12 07:28 UTC, laoneo commented on administrator/components/com_media/models/api.php
> +			$config['fileadapter'] = $adapters;
Same here. This assignment is not needed at all. It makes sense when you want to inject the adapters trough the config.

2017-06-12 07:28 UTC, laoneo commented on administrator/components/com_media/views/media/view.html.php
> +		$this->providers = $this->getProviders();
No need to do it in the constructor, better in the display function.

2017-06-12 07:28 UTC, laoneo commented on administrator/components/com_media/views/media/view.html.php
> +	public function getProviders()
This function needs to be moved to the model. Then you can do in this class `$this->providers = $this->get('Providers');`

2017-06-12 07:28 UTC, laoneo commented on administrator/components/com_media/views/media/view.html.php
> +		return json_encode((array) $results);
This needs to be moved to the default.php file.

2017-06-12 07:28 UTC, laoneo commented on administrator/components/com_media/views/media/view.html.php
> +
Why this extra new line?

2017-06-12 07:28 UTC, laoneo commented on administrator/components/com_media/views/media/view.html.php
> +
One empty line to much.

2017-06-12 07:28 UTC, kasvith commented on administrator/components/com_media/models/api.php
> +		throw new Exception('Requested media file adapter was not found', 500);
Sure

2017-06-12 07:29 UTC, laoneo commented on administrator/components/com_media/models/api.php
> +			$this->adapters = $adapters;
It was different in the actual implementation. How I did it was to allow to inject the adapter.

2017-06-12 07:43 UTC, laoneo commented on administrator/components/com_media/models/api.php
> +			$this->adapters = $adapters;
For me it makes sense to have a config option, it allows to inject the adapters and providers trough the constructor. But you need to follow the recommendation from @dneukirchen.

2017-06-12 07:47 UTC, laoneo commented on administrator/components/com_media/models/api.php
> +	public function getProviders()
Where is this function needed? Where do we need the providers at all in the api layer?

2017-06-12 13:42 UTC, kasvith commented on administrator/components/com_media/controllers/api.json.php
> +		list($adapter, $account)  = array_merge(explode('-', $adapterInfo), array(""));
this code will try to extract an account info if it presents, we will use this ASAP

2017-06-12 13:49 UTC, kasvith commented on administrator/components/com_media/controllers/api.json.php
> +		list($adapter, $account)  = array_merge(explode('-', $adapterInfo), array(""));
we can replace this with `list($adapter) = $adapterInfo` if you want

2017-06-12 14:09 UTC, laoneo commented on administrator/components/com_media/controllers/api.json.php
> +		list($adapter, $account)  = array_merge(explode('-', $adapterInfo), array(""));
Better to use only code which is in use actually, when we need it then we can add it at that time.

2017-06-12 14:10 UTC, laoneo commented on administrator/components/com_media/models/api.php
> +		if (!isset($this->adapters[$adapter]))
Is this needed? You don't do the check on the other functions?

2017-06-12 14:12 UTC, laoneo requested changes

2017-06-12 14:12 UTC, laoneo commented on administrator/components/com_media/models/api.php
> +		if (!isset($this->adapters[$adapter]))
Is this needed? You don't do the check on the other functions?

2017-06-12 14:12 UTC, laoneo commented on administrator/components/com_media/views/media/tmpl/default.php
> +	'providers'               => json_encode((array) $this->get('providers')),
Here you have to do `$this->providers`.

2017-06-12 14:12 UTC, laoneo commented on administrator/language/en-GB/en-GB.plg_filesystem_local.ini
> +PLG_FILESYSTEM_LOCAL_DISPLAY_NAME_DESC = "Local Filesystem plugin"
It needs an empty line at the end of the file.

2017-06-12 14:16 UTC, kasvith commented on administrator/components/com_media/models/api.php
> +		if (!isset($this->adapters[$adapter]))
yep we need to send an empty array for frontend if adapter is not set

2017-06-12 14:34 UTC, laoneo commented on administrator/components/com_media/models/api.php
> +		$this->providers = $config['providers'];
What's the purpose of the providers in this class?

2017-06-12 14:35 UTC, laoneo commented on administrator/components/com_media/models/media.php
> +	protected $providers = null;
What do you need that for?

2017-06-12 14:37 UTC, laoneo commented on administrator/components/com_media/models/api.php
> +		if (!isset($this->adapters[$adapter]))
Why not throw the exception when the adapter doesn't exist?

2017-06-12 14:44 UTC, kasvith commented on administrator/components/com_media/models/api.php
> +		$this->providers = $config['providers'];
we will need it for multiple accounts soon

2017-06-12 14:45 UTC, kasvith commented on administrator/components/com_media/models/media.php
> +	protected $providers = null;
for multiple accounts we need it

2017-06-12 14:49 UTC, kasvith commented on administrator/language/en-GB/en-GB.plg_filesystem_local.ini
> +PLG_FILESYSTEM_LOCAL_DISPLAY_NAME_DESC = "Local Filesystem plugin"
done

2017-06-12 15:24 UTC, laoneo commented on administrator/components/com_media/models/media.php
> +	protected $providers = null;
I don't see a place where this variable is used.

2017-06-12 15:24 UTC, laoneo commented on administrator/language/en-GB/en-GB.plg_filesystem_local.ini
> +; Joomla! Project; Copyright (C) 2005 - 2017 Open Source Matters. All rights reserved.; License GNU General Public License version 2 or later; see LICENSE.txt, see LICENSE.php; Note : All ini file
Guess you screwed it up here

2017-06-12 15:25 UTC, laoneo commented on administrator/components/com_media/models/api.php
> +	protected $providers = null;
Where is this variable used?

2017-06-12 15:26 UTC, kasvith commented on administrator/language/en-GB/en-GB.plg_filesystem_local.ini
> +; Joomla! Project; Copyright (C) 2005 - 2017 Open Source Matters. All rights reserved.; License GNU General Public License version 2 or later; see LICENSE.txt, see LICENSE.php; Note : All ini file
seems crlf was used, fixed asap

2017-06-12 15:28 UTC, kasvith commented on administrator/components/com_media/models/api.php
> +	protected $providers = null;
not used at the moment, for multiple accounts i decided to use it

2017-06-12 15:29 UTC, kasvith commented on administrator/components/com_media/models/media.php
> +	protected $providers = null;
yep ATM it has not used, i'll remove it

2017-06-12 17:13 UTC, merged

2017-06-12 17:13 UTC, dneukirchen commented
good job @kasvith

2017-06-12 17:14 UTC, kasvith commented
thank you @dneukirchen