Feature/oauthcallback
joomla-projects/media-manager-improvement pull request #280
Opened 2017-08-16 01:04 UTC by kasvith

### Summary of Changes
Added OAuthCallback endpoint to Joomla!

From now on 3rd Party Plugin developers can simply can get data from a redirect without using any controller written by them.

Developers can set redirect uri for 
**_[site-name]/administrator/index.php?option=com_media&task=plugin.oauthcallback&plugin=[plugin-name]_**

To send a request to Joomla, you must also set the state parameter of your cloud provider.
This is used common across  cloud providers to keep the consistent of the data. In this case put *token* request by `\JSession::getFormToken()` as **state**  in order to access Joomla from this callback.

Once successfully CSRF token is verified, your plugin will receive all the data passed to the callback.
For that your plugin must implement the following method

```
public function onFilesystemOAuthCallback(\Joomla\Component\Media\Administrator\Event\OAuthCallbackEvent $event)
{
     	// your code
	
	$result = $event->getArguments('result', []); // prevent overwriting existing results if any
	$result[] = 'your result';
	$event->setArguments('result', $result);
}
```

**result** is a special variable you need to set. Do not use legacy return along with this. It will not work. In any case read this [gist](https://gist.github.com/kasvith/1217c31414cfcece82fd5565b70ff80a)

Result defines the way Joomla behaves after a successful method call.

- 'action'
   Set this to 
   - close : Closes a window which is opened by a Java Script using *window.open()*
   - redirect : Redirects to the page specified by the *redirect_uri*
   - control-panel : Redirect to control panel
   - media-manager : Redirect to Media Manager

- 'redirect_uri'
   Used with *redirect* action (required)

- 'message'
   Message need to be displayed after an action

- 'message_type'
   - warning
   - notice
   - error
   - message(or set empty)

### Testing Instructions
Please comment out CSRF checking in Controller/Plugin.php and start navigating callback using url structure provided above.

### Expected result

### Actual result

### Documentation Changes Required

2017-08-16 15:36 UTC, laoneo requested changes

2017-08-16 15:36 UTC, laoneo commented on administrator/components/com_media/Controller/Plugin.php
> +use League\Flysystem\Exception;
Please use core exceptions.

2017-08-16 15:36 UTC, laoneo commented on administrator/components/com_media/Controller/Plugin.php
> +		if (!isset($input['status']))
Is this not google drive specific?

2017-08-16 15:36 UTC, laoneo commented on administrator/components/com_media/Controller/Plugin.php
> +		if (\JSession::getFormToken() != $input['status'])
Is this not google drive specific?

2017-08-16 15:36 UTC, laoneo commented on administrator/components/com_media/Controller/Plugin.php
> +			$eventResults = (array) \JFactory::getApplication()->triggerEvent('onFilesystemOAuthCallback', $event);
Please use the namespaced Factory.

2017-08-16 15:36 UTC, laoneo commented on administrator/components/com_media/tmpl/plugin/default.php
> +<?php
When is this view used?

2017-08-16 15:40 UTC, kasvith commented on administrator/components/com_media/Controller/Plugin.php
> +		if (!isset($input['status']))
nope

2017-08-16 15:40 UTC, kasvith commented on administrator/components/com_media/Controller/Plugin.php
> +		if (\JSession::getFormToken() != $input['status'])
nope

2017-08-16 15:40 UTC, kasvith commented on administrator/components/com_media/tmpl/plugin/default.php
> +<?php
when in action *close* used

2017-08-16 15:41 UTC, kasvith commented on administrator/components/com_media/Controller/Plugin.php
> +use League\Flysystem\Exception;
Sorry it was done by IDE

2017-08-16 15:52 UTC, kasvith commented on administrator/components/com_media/tmpl/plugin/default.php
> +<?php
it can be used by 3dps to close any new window opened by themselves with a single line of code

2017-08-17 11:43 UTC, laoneo commented on administrator/components/com_media/Controller/Plugin.php
> +		if (!isset($input['status']))
So what happens when a cloud doesn't support the status flag? I guess it will not work.

2017-08-17 13:23 UTC, merged

2017-08-17 13:23 UTC, laoneo commented
Thanks!!

2017-08-17 13:31 UTC, kasvith commented
You are welcome

2017-08-17 14:58 UTC, dneukirchen commented
thx @kasvith